import json
import os

domains_data = [
    {
        "domain": "Healthcare & Biomedical AI",
        "ideas": [
            ("EdgeMed: Real-Time Chest Radiograph Triage with INT8 Quantization", 
             "Local hospital triage pipeline that classifies 14 thoracic pathologies from DICOM images on CPU using INT8 ONNX models with Grad-CAM visual attention overlays.",
             {"python": 3, "pytorch": 3, "onnx_runtime": 3, "fastapi": 2, "opencv": 2}, 16, "CPU-only", 4, True, ["Python", "ONNX Runtime", "FastAPI", "PyTorch", "OpenCV", "React"]),
            ("PulseGuard: Continuous Arrhythmia Detection from Single-Lead ECG",
             "Edge inference firmware filtering raw analog ECG voltages, extracting RR intervals, and classifying atrial fibrillation episodes using 1D temporal convolutions.",
             {"python": 3, "tinyml": 3, "esp32": 3, "embedded_c": 3, "sensors_protocols": 2}, 14, "IoT hardware", 4, True, ["Embedded C", "ESP32", "TinyML", "MQTT", "Python"]),
            ("BioSync: Multi-Modal Patient Fall and Vitals Telemetry via BLE Mesh",
             "Wearable accelerometer and photoplethysmography sensor network streaming encrypted patient vitals over BLE mesh to an emergency room triage dashboard.",
             {"embedded_c": 3, "esp32": 3, "mqtt": 3, "timescaledb": 2, "fastapi": 2}, 16, "IoT hardware", 5, False, ["ESP32", "C++", "MQTT", "TimescaleDB", "FastAPI", "React"]),
            ("DermaScan: Dermoscopic Lesion Segmentation with Uncertainty Calibration",
             "Melanoma boundary delineation using Monte Carlo dropout segmentation networks to provide dermatologist confidence bounds for biopsy referrals.",
             {"python": 4, "pytorch": 3, "opencv": 3, "fastapi": 2}, 14, "GPU available", 3, True, ["PyTorch", "OpenCV", "FastAPI", "Docker", "React"]),
            ("NeuroSpeech: Dysarthria Acoustic Biomarker Extraction for ALS Monitoring",
             "Speech signal processing pipeline extracting jitter, shimmer, and formant trajectories to detect motor neuron degeneration progression non-invasively.",
             {"python": 3, "pandas_numpy": 3, "scikit_learn": 3, "fastapi": 2}, 12, "CPU-only", 3, True, ["Python", "Librosa", "Scikit-Learn", "FastAPI", "Recharts"]),
            ("SurgiTrack: Sub-Millimeter Laparoscopic Instrument Visual Tracking",
             "Optical flow and color marker-free surgical tool tip tracking in stereo endoscopic video feeds for real-time surgical tremor dampening.",
             {"cpp": 3, "opencv": 4, "pytorch": 3}, 18, "GPU available", 4, True, ["C++", "OpenCV", "PyTorch", "CUDA"]),
            ("PharmAlert: Automated Drug-Drug Interaction Discovery via Biomedical KG",
             "Graph convolutional neural network over PubMed biomedical knowledge graphs discovering adverse contraindications in polypharmacy patient regimens.",
             {"python": 4, "pytorch": 3, "vector_databases": 3, "postgresql": 2}, 16, "CPU-only", 4, True, ["Python", "PyTorch Geometric", "PostgreSQL", "FastAPI"]),
            ("GaitLab: Markerless 3D Biomechanical Gait Kinematics from Monocular Video",
             "Pose estimation pipeline reconstructing lower-extremity joint angle trajectories to assist post-stroke rehabilitation physical therapy.",
             {"python": 3, "opencv": 3, "pytorch": 3, "data_viz": 3}, 14, "GPU available", 4, True, ["Python", "PyTorch", "OpenCV", "FastAPI", "D3.js"]),
            ("Audiolyze: Real-Time Cochlear Acoustic Feedback for Pediatric Speech Therapy",
             "Low-latency pitch and phonetic spectrum visualization guiding children with hearing impairments to modulate vocal resonance.",
             {"typescript": 3, "react": 3, "data_viz": 3, "web_performance": 3}, 10, "none", 3, False, ["React", "Web Audio API", "TypeScript", "D3.js"]),
            ("HemoCount: Microfluidic Blood Smear Cell Counting with Synthetic Augmentation",
             "Automated complete blood count (CBC) from digitized microscope glass slides using synthetic diffusion augmentation to train white cell counters.",
             {"python": 4, "pytorch": 4, "opencv": 3, "fastapi": 2}, 16, "GPU available", 4, True, ["PyTorch", "OpenCV", "FastAPI", "Docker"])
        ]
    },
    {
        "domain": "Edge AI & TinyML / IoT",
        "ideas": [
            ("AeroSense: Ultra-Low-Power Wildfire Smoke Detection via TinyML Sensor Fusion",
             "Off-grid ESP32 sensor node fusing particulate matter, CO2, and temperature readings with an onboard 12KB neural classifier powered by solar harvesting.",
             {"embedded_c": 3, "esp32": 3, "tinyml": 3, "sensors_protocols": 3, "mqtt": 2}, 14, "IoT hardware", 4, True, ["Embedded C", "ESP32", "TinyML", "MQTT", "TimescaleDB"]),
            ("VibroGuard: Predictive Industrial Motor Bearing Failure via Edge FFT",
             "MEMS vibration accelerometer sampling at 10kHz on STM32/ESP32 computing spectral kurtosis and alerting technicians before bearing seizure.",
             {"embedded_c": 4, "esp32": 3, "tinyml": 3, "sensors_protocols": 3}, 16, "IoT hardware", 4, True, ["Embedded C", "CMSIS-DSP", "ESP32", "MQTT"]),
            ("SoundSentinel: Acoustic Edge Gunshot & Chainsaw Localization",
             "Microphone array triangulation running on Raspberry Pi edge devices using generalized cross-correlation phase transform (GCC-PHAT) for rainforest anti-poaching.",
             {"python": 3, "raspberry_pi": 3, "linux_admin": 2, "tinyml": 2}, 16, "IoT hardware", 4, True, ["Python", "Raspberry Pi", "NumPy", "FastAPI"]),
            ("AgriDrip: Autonomous LoRa Soil Moisture and Evapotranspiration Controller",
             "Sub-gigahertz LoRa sensor nodes estimating soil water deficit and triggering solenoid irrigation valves strictly during off-peak thermal hours.",
             {"embedded_c": 3, "sensors_protocols": 3, "esp32": 3}, 12, "IoT hardware", 3, False, ["Embedded C", "LoRaWAN", "ESP32", "SQLite"]),
            ("ColdChain: Pharmaceutical Cryo-Transport Logger with Tamper Proof Cryptography",
             "BLE sensor beacon logging cryogenic vaccine temperatures into an append-only cryptographic hash chain with NFC validation on delivery.",
             {"embedded_c": 3, "esp32": 3, "sensors_protocols": 2}, 12, "IoT hardware", 3, False, ["Embedded C", "ESP32", "BLE", "Python"]),
            ("SmartMeter: Edge Non-Intrusive Load Monitoring (NILM) on Microcontrollers",
             "Current transformer clamp sampling household AC waveforms to disaggregate individual appliance electricity consumption without smart plugs.",
             {"python": 3, "tinyml": 3, "esp32": 3, "timescaledb": 2}, 16, "IoT hardware", 4, True, ["Python", "TinyML", "ESP32", "TimescaleDB"]),
            ("BeeTrack: Non-Invasive Acoustic Colony Collapse Warning System",
             "In-hive acoustic sensor running an INT8 quantized resonant frequency detector to detect queen bee loss and parasite infestations.",
             {"embedded_c": 3, "esp32": 3, "tinyml": 3, "mqtt": 2}, 14, "IoT hardware", 3, True, ["Embedded C", "ESP32", "TinyML", "MQTT"]),
            ("HoloTouch: Ultrasonic Gesture Interface for Sterile Surgical Displays",
             "Time-of-flight ultrasonic sensor array detecting 3D hand gestures to control PACS medical imaging monitors touchlessly in operating theaters.",
             {"cpp": 3, "embedded_c": 3, "esp32": 3}, 14, "IoT hardware", 3, False, ["C++", "ESP32", "I2C", "WebSockets"]),
            ("UrbanFlow: Privacy-Preserving Pedestrian Density Radar via mmWave",
             "60GHz FMCW millimeter-wave radar sensor counting pedestrian flow through public transit stations without capturing optical images.",
             {"python": 3, "raspberry_pi": 3, "timescaledb": 2}, 14, "IoT hardware", 3, False, ["Python", "Raspberry Pi", "TimescaleDB", "Grafana"]),
            ("FleetPulse: CAN-Bus Edge Telematics and Predictive Fleet Diagnostics",
             "OBD-II CAN-bus reader parsing engine telemetry frames and predicting battery degradation using lightweight linear regression on edge SBCs.",
             {"python": 3, "embedded_c": 3, "raspberry_pi": 3, "mqtt": 2}, 14, "IoT hardware", 4, False, ["Python", "CAN-bus", "Raspberry Pi", "FastAPI"])
        ]
    },
    {
        "domain": "Autonomous Systems & Robotics",
        "ideas": [
            ("SwarmSync: Decentralized Consensus for Aerial Drone Flocking without GPS",
             "Peer-to-peer visual odometry and ultra-wideband (UWB) ranging protocol allowing 5 quadcopters to maintain tight formation in indoor tunnels.",
             {"cpp": 4, "opencv": 3, "linux_admin": 3}, 20, "GPU available", 5, True, ["C++", "ROS2", "OpenCV", "Linux"]),
            ("WarehouseRover: Autonomous Mobile Robot with Dynamic A* and Semantic Costmaps",
             "2D LiDAR SLAM wheeled mobile robot navigating unpredictable fulfillment center aisles while recognizing forklift yield zones.",
             {"cpp": 3, "python": 3, "opencv": 3, "linux_admin": 2}, 18, "CPU-only", 4, False, ["C++", "ROS2 Nav2", "Python", "LiDAR"]),
            ("AgriBot: Precision Weed Eradication via Stereo Vision and Delta Arm",
             "Agricultural rover identifying invasive weeds among sugar beet crops using lightweight object detection and triggering a targeted spray nozzle.",
             {"python": 3, "pytorch": 3, "opencv": 3, "embedded_c": 2}, 16, "GPU available", 5, True, ["Python", "PyTorch", "OpenCV", "ESP32"]),
            ("RoboGrip: Tactile Slip Detection for Soft Robotic Grippers",
             "Piezoresistive sensor skin measuring micro-vibrations to dynamically adjust grasping force before fragile glass objects slip from robot claws.",
             {"cpp": 3, "embedded_c": 3, "sensors_protocols": 3}, 14, "IoT hardware", 4, True, ["C++", "Embedded C", "I2C", "Python"]),
            ("CaveMapper: Autonomous Subterranean Exploration using Quadruped Robots",
             "3D point cloud registration and frontier-based exploration algorithm mapping abandoned mineshafts with zero operator tether.",
             {"cpp": 4, "linux_admin": 3, "opencv": 3}, 20, "GPU available", 5, True, ["C++", "ROS2", "PCL", "CUDA"]),
            ("DockMaster: Vision-Guided Precision Autonomous Underwater Vehicle Docking",
             "Monocular underwater camera locating acoustic transponder docking bays amidst turbid water using dark-channel dehazing algorithms.",
             {"python": 3, "opencv": 3, "pytorch": 3}, 16, "GPU available", 4, True, ["Python", "OpenCV", "PyTorch", "ROS2"]),
            ("CableClimber: High-Voltage Transmission Line Inspection Robot",
             "Robotic crawler traversing 110kV suspension cables, logging corrosion pits and insulator flashover cracks using high-res stereo cameras.",
             {"embedded_c": 3, "opencv": 3, "esp32": 3}, 16, "IoT hardware", 4, False, ["Embedded C", "OpenCV", "ESP32", "Python"]),
            ("ExoSense: Active Lower-Limb Exoskeleton with Surface EMG Intent Recognition",
             "Multi-channel electromyography muscle potential decoder anticipating leg swing phases to drive brushless DC motors for mobility assistance.",
             {"embedded_c": 4, "tinyml": 3, "sensors_protocols": 3}, 18, "IoT hardware", 5, True, ["Embedded C", "TinyML", "STM32", "Python"]),
            ("AeroTrack: Drone Intrusion Detection via Multi-Camera Stereo Triangulation",
             "Coordinated dual PTZ security cameras tracking rogue recreational UAVs in restricted airspace with kalman filter trajectory projection.",
             {"python": 3, "opencv": 4, "fastapi": 2}, 14, "GPU available", 4, True, ["Python", "OpenCV", "FastAPI", "WebSockets"]),
            ("TrashSail: Autonomous Solar Catamaran for Harbor Plastic Skimming",
             "Autonomous surface vessel utilizing monocular computer vision to navigate marina debris booms and scoop floating macro-plastics.",
             {"python": 3, "opencv": 3, "raspberry_pi": 3, "sensors_protocols": 2}, 16, "IoT hardware", 4, False, ["Python", "OpenCV", "Raspberry Pi", "MQTT"])
        ]
    },
    {
        "domain": "Cybersecurity & Threat Intelligence",
        "ideas": [
            ("KernelShield: eBPF Real-Time Container Privilege Escalation Interceptor",
             "Linux security agent attaching eBPF tracepoints to syscalls (execve, ptrace) to kill malicious processes breaking out of Docker namespaces.",
             {"golang": 3, "linux_admin": 4, "docker": 3}, 16, "CPU-only", 4, True, ["Go", "eBPF", "Linux Cgroups", "Docker", "Prometheus"]),
            ("PhishHunter: Deep Visual Similarity and Domain Homograph Defense",
             "Browser extension rendering web pages in headless Chrome, computing perceptual hashes against brand vector logos to block zero-day credential harvesters.",
             {"typescript": 3, "python": 3, "fastapi": 2, "opencv": 2}, 14, "CPU-only", 3, True, ["TypeScript", "Python", "FastAPI", "OpenCV"]),
            ("HoneyNet: Dynamic Deception Environment for ICS/SCADA Modbus Honeypots",
             "Configurable virtual PLC honeynet simulating water treatment telemetry to profile adversary reconnaissance tactics and log zero-day exploits.",
             {"python": 3, "linux_admin": 3, "docker": 3, "data_viz": 2}, 14, "CPU-only", 4, False, ["Python", "Docker", "Scapy", "FastAPI", "React"]),
            ("GhostPacket: Covert Channel Detection in DNS and ICMP Payloads",
             "Deep inspection IDS engine extracting entropy, inter-packet arrival jitter, and n-gram frequencies to flag data exfiltration via DNS tunneling.",
             {"python": 3, "scikit_learn": 3, "linux_admin": 3}, 12, "CPU-only", 3, True, ["Python", "Scapy", "Scikit-Learn", "FastAPI"]),
            ("ZeroTrustGate: Ephemeral WireGuard Mesh with Hardware-Attested WebAuthn",
             "Micro-segmented internal VPN creating per-session WireGuard tunnels strictly upon FIDO2 biometric authentication and device TPM posture checks.",
             {"golang": 3, "linux_admin": 3, "react": 2}, 14, "CPU-only", 4, False, ["Go", "WireGuard", "WebAuthn", "SQLite", "React"]),
            ("FirmScope: Automated IoT Firmware Vulnerability Scanner and Emulation Engine",
             "Static extraction of squashfs filesystem images, binary decompilation for hardcoded credentials, and QEMU emulation of MIPS/ARM binaries.",
             {"python": 4, "bash": 3, "linux_admin": 3, "docker": 3}, 16, "CPU-only", 4, False, ["Python", "QEMU", "Bash", "FastAPI", "React"]),
            ("SupplyGuard: Automated SBOM Verification and Dependency Typosquatting Sentinel",
             "Continuous CI/CD scanner parsing npm/PyPI dependency trees, flagging malicious lifecycle post-install scripts and brandjacking package names.",
             {"typescript": 3, "python": 3, "cicd": 3, "docker": 2}, 12, "none", 3, True, ["TypeScript", "Python", "GitHub Actions", "Docker"]),
            ("CanaryVault: Cryptographic Ransomware Early-Warning Sentinel via Honeyfiles",
             "Filesystem minifilter driver deploying honeydoc canary files in network shares to detect rapid entropy surges and kill encrypting PIDs.",
             {"cpp": 4, "linux_admin": 3, "bash": 2}, 14, "CPU-only", 3, True, ["C++", "Linux inotify", "Bash", "SQLite"]),
            ("API-WAF: Adaptive Behavioral Rate Limiting and BOLA Attack Detector",
             "Reverse proxy analyzing API request sequence graphs and token claims to block Broken Object Level Authorization (BOLA) attempts in real time.",
             {"golang": 3, "redis": 3, "rest_apis": 3, "docker": 2}, 14, "CPU-only", 4, True, ["Go", "Redis", "Docker", "REST APIs"]),
            ("LeakWatch: Enterprise Secret Sprawl Scanner for Ephemeral CI Runners",
             "Git pre-commit and pipeline hook utilizing Shannon entropy and AST regexes to intercept JWTs, AWS credentials, and private keys before push.",
             {"golang": 3, "cicd": 3, "bash": 2}, 10, "none", 2, False, ["Go", "Git Hooks", "GitHub Actions"])
        ]
    },
    {
        "domain": "FinTech & Fraud Analytics",
        "ideas": [
            ("GraphFraud: Real-Time Anti-Money Laundering via Temporal Graph Neural Networks",
             "Continuous graph learning engine tracking money laundering transaction rings across 500k bank accounts with dynamic edge time-decay weighting.",
             {"python": 4, "pytorch": 3, "postgresql": 3, "timescaledb": 2}, 16, "CPU-only", 4, True, ["Python", "PyTorch Geometric", "PostgreSQL", "FastAPI"]),
            ("LedgerSense: Zero-Knowledge Proof Audit Trail for Corporate Treasury",
             "zk-SNARK cryptographic verification layer proving company balance sheet solvency without revealing individual customer transaction records.",
             {"rust": 4, "typescript": 3, "react": 2}, 16, "none", 3, True, ["Rust", "Circom / SnarkJS", "TypeScript", "React"]),
            ("OrderBook: High-Frequency Limit Order Book Simulation with Microstructure Alpha",
             "Lock-free C++ matching engine processing 1,000,000 orders/sec with nanosecond timestamps to backtest market-making inventory strategies.",
             {"cpp": 4, "data_viz": 3}, 14, "CPU-only", 3, True, ["C++20", "Lock-free Queues", "Python", "Recharts"]),
            ("PaySentry: Real-Time Chargeback & Synthetic Identity Fraud Classifier",
             "Payment gateway scoring API combining device fingerprinting, behavioral mouse trajectory entropy, and ensemble gradient boosting in under 40ms.",
             {"python": 3, "scikit_learn": 3, "fastapi": 3, "redis": 3}, 12, "CPU-only", 4, False, ["Python", "Scikit-Learn", "FastAPI", "Redis"]),
            ("QuantStream: Decentralized Oracle Consensus for Synthetic Commodity Assets",
             "Multi-source financial market aggregator discarding outlier quote spikes using Median Absolute Deviation before publishing price feeds.",
             {"golang": 3, "rest_apis": 3, "timescaledb": 2}, 12, "none", 3, False, ["Go", "WebSockets", "TimescaleDB", "REST APIs"]),
            ("TaxEngine: Multi-Jurisdictional Cross-Border VAT and Crypto Compliance",
             "Automated tax lot accounting engine computing FIFO, LIFO, and Specific ID capital gains across 10 distinct blockchain protocols.",
             {"python": 3, "sql": 3, "postgresql": 3, "react": 2}, 12, "none", 3, False, ["Python", "PostgreSQL", "FastAPI", "React"]),
            ("MicroScore: Alternative Underwriting Engine for Unbanked Micro-Merchants",
             "Creditworthiness scoring pipeline analyzing utility payment regularity, mobile airtime recharges, and localized supply chain receipts.",
             {"python": 3, "pandas_numpy": 3, "scikit_learn": 3, "fastapi": 2}, 12, "CPU-only", 3, False, ["Python", "Pandas", "Scikit-Learn", "FastAPI"]),
            ("RiskMatrix: Real-Time Value-at-Risk (VaR) Monte Carlo Portfolio Engine",
             "Vectorized NumPy simulation executing 100,000 correlated price shock scenarios to compute Expected Shortfall for multi-asset portfolios.",
             {"python": 3, "pandas_numpy": 4, "fastapi": 2, "data_viz": 3}, 12, "CPU-only", 3, True, ["Python", "NumPy", "FastAPI", "D3.js"]),
            ("FairLend: Algorithmic Bias Detection and Counterfactual Parity in Lending",
             "Fairness auditing toolkit analyzing credit scoring models for disparate impact across protected demographic attributes with disparate impact repair.",
             {"python": 3, "scikit_learn": 3, "data_viz": 3}, 10, "none", 2, True, ["Python", "Scikit-Learn", "FastAPI", "Recharts"]),
            ("AlgoGuard: Market Manipulation Sentinel for Spoofing and Wash Trading",
             "Real-time order flow inspection detecting quote stuffing, layering, and cancelled trades designed to mislead automated algorithms.",
             {"python": 3, "timescaledb": 3, "fastapi": 2, "redis": 2}, 14, "CPU-only", 4, True, ["Python", "TimescaleDB", "Redis", "FastAPI"])
        ]
    },
    {
        "domain": "Green Tech & Renewable Smart Grids",
        "ideas": [
            ("GridPulse: Physics-Informed Solar Inverter Telemetry and Islanding Prevention",
             "Hybrid neural forecasting and Kirchhoff law simulator managing bi-directional power flows and battery discharging in neighborhood microgrids.",
             {"python": 3, "pytorch": 3, "timescaledb": 3, "mqtt": 2}, 16, "CPU-only", 4, True, ["Python", "PyTorch", "TimescaleDB", "MQTT", "React"]),
            ("EV-ChargeFlow: Smart Grid Dynamic EV Charging Orchestration",
             "Non-linear optimization service scheduling 50 fleet vehicle chargers to prevent substation transformer overload during peak tariff windows.",
             {"python": 4, "fastapi": 3, "redis": 2, "data_viz": 2}, 14, "none", 3, True, ["Python", "SciPy Optimize", "FastAPI", "Redis", "React"]),
            ("BioGasTrack: Anaerobic Digester Methane Yield Optimization via Sensor Loop",
             "IoT telemetry controller monitoring pH, slurry temperature, and volatile fatty acids to maximize biomethane generation in agricultural digesters.",
             {"embedded_c": 3, "esp32": 3, "timescaledb": 2, "mqtt": 2}, 14, "IoT hardware", 4, False, ["Embedded C", "ESP32", "TimescaleDB", "MQTT"]),
            ("WindTurbinePredict: Acoustic Blade Delamination Sentinel via Edge FFT",
             "Wind turbine nacelle vibration and audio sensor detecting micro-cracks in 40m fiberglass blades prior to catastrophic structural failure.",
             {"embedded_c": 3, "esp32": 3, "tinyml": 3, "sensors_protocols": 2}, 16, "IoT hardware", 4, True, ["Embedded C", "ESP32", "TinyML", "TimescaleDB"]),
            ("CarbonLedger: Scope 1, 2, and 3 Enterprise Carbon Footprint Auditing API",
             "Automated greenhouse gas accounting engine digesting ERP invoices, electricity meter data, and travel logs into standardized GHG Protocol reports.",
             {"python": 3, "postgresql": 3, "fastapi": 3, "react": 2}, 12, "none", 3, False, ["Python", "PostgreSQL", "FastAPI", "React"]),
            ("HydroFlow: Run-of-River Micro-Hydro Turbine Adaptive Incline Governor",
             "Motorized penstock valve controller adjusting water intake based on upstream ultrasonic river depth sensors and grid frequency demand.",
             {"cpp": 3, "embedded_c": 3, "esp32": 3}, 14, "IoT hardware", 3, False, ["C++", "ESP32", "FreeRTOS", "Modbus"]),
            ("SolarSentry: Drone Thermal Orthomosaic Solar Farm Hotspot Detection",
             "Computer vision pipeline stitching radiometric infrared drone imagery to automatically flag bypass diode failures and cracked PV cells.",
             {"python": 3, "opencv": 4, "pytorch": 3}, 16, "GPU available", 4, True, ["Python", "OpenCV", "PyTorch", "FastAPI"]),
            ("CoolBuilding: Predictive HVAC Thermostat via Ambient Thermal Inertia Modeling",
             "Thermodynamic building envelope simulator pre-cooling commercial spaces during cheap morning solar hours to minimize 4PM peak grid stress.",
             {"python": 3, "pandas_numpy": 3, "scikit_learn": 3, "fastapi": 2}, 12, "CPU-only", 3, True, ["Python", "Pandas", "Scikit-Learn", "FastAPI"]),
            ("BatteryTwin: Lithium-Ion Degradation & Remaining Useful Life (RUL) Digital Twin",
             "Electrochemical battery degradation tracker estimating state-of-health (SoH) from partial discharge voltage relaxation curves.",
             {"python": 3, "pandas_numpy": 3, "timescaledb": 2, "data_viz": 3}, 14, "CPU-only", 3, True, ["Python", "NumPy", "TimescaleDB", "D3.js"]),
            ("RecycleSort: High-Speed Waste Material NIR Optical Sorter",
             "Near-infrared spectral reflectance classifier triggering high-pressure pneumatic ejector nozzles to separate PET, HDPE, and PP plastics.",
             {"python": 3, "opencv": 3, "embedded_c": 3, "raspberry_pi": 3}, 16, "IoT hardware", 4, True, ["Python", "OpenCV", "Raspberry Pi", "ESP32"])
        ]
    },
    {
        "domain": "Distributed Systems & Cloud Infrastructure",
        "ideas": [
            ("MiniRaft: Resilient Distributed Consensus Key-Value Store in Go",
             "Production-grade implementation of Raft consensus featuring leader election, append-only log replication, snapshotting, and fault injection.",
             {"golang": 4, "linux_admin": 3, "docker": 2}, 16, "CPU-only", 4, True, ["Go", "gRPC", "Docker", "Linux"]),
            ("LoadMesh: Consistent Hashing Distributed Cache with Rendezvous Routing",
             "In-memory distributed LRU cache utilizing Ketama consistent hashing, heartbeat failure detection, and probabilistic bloom filters.",
             {"golang": 3, "asyncio": 2, "docker": 3}, 14, "CPU-only", 3, True, ["Go", "Consistent Hashing", "Docker", "Prometheus"]),
            ("TaskQueue: Zero-Dependency Distributed Task Queue with Priority Leasing",
             "Durable task execution broker implementing distributed lock leases, exponential backoff retries, and dead-letter queues over SQLite WAL.",
             {"python": 3, "asyncio": 3, "fastapi": 3, "redis": 2}, 12, "CPU-only", 3, False, ["Python", "asyncio", "FastAPI", "SQLite", "React"]),
            ("EdgeSync: Conflict-Free Replicated Data Types (CRDT) Collaborative Document Store",
             "State-based and operation-based CRDT engine enabling real-time peer-to-peer document editing across disconnected clients without central locks.",
             {"typescript": 4, "websockets": 3, "react": 3}, 14, "none", 3, True, ["TypeScript", "WebSockets", "CRDT", "React"]),
            ("MetricPulse: High-Throughput Time-Series Metric Ingestion & Downsampling Daemon",
             "Lightweight metric aggregator buffering 100,000 UDP statsd metrics/sec, computing exponential moving averages and writing to disk.",
             {"rust": 4, "linux_admin": 3, "observability": 3}, 16, "CPU-only", 3, True, ["Rust", "Linux Sockets", "Prometheus", "Grafana"]),
            ("ChaosPod: Kubernetes Chaos Engineering Operator for StatefulSets",
             "Kubernetes custom controller injecting network packet latency, pod evictions, and disk I/O throttling to validate cluster self-healing.",
             {"golang": 4, "kubernetes": 4, "docker": 3}, 16, "none", 4, False, ["Go", "Kubernetes Operator SDK", "Docker"]),
            ("BlobStore: S3-Compatible Content-Addressable Object Storage Engine",
             "High-performance chunked blob store with SHA-256 deduplication, Reed-Solomon erasure coding, and multipart HTTP upload streams.",
             {"golang": 3, "rest_apis": 3, "linux_admin": 3}, 16, "CPU-only", 4, True, ["Go", "Erasure Coding", "REST APIs", "Docker"]),
            ("MicroTrace: Zero-Instrumentation eBPF Distributed Request Tracer",
             "Kernel-level tracer extracting HTTP request headers and tracing latency across microservices without modifying application source code.",
             {"golang": 3, "linux_admin": 4, "observability": 3}, 18, "CPU-only", 4, True, ["Go", "eBPF", "OpenTelemetry", "Linux"]),
            ("LogPipe: Append-Only Partitioned Commit Log with Zero-Copy Reads",
             "Kafka-like distributed message broker utilizing Linux sendfile zero-copy system calls and memory-mapped index segments.",
             {"rust": 4, "linux_admin": 3}, 16, "CPU-only", 3, True, ["Rust", "mmap", "Linux Syscalls"]),
            ("CanaryMesh: Intelligent Automated Traffic Shifting Service Mesh",
             "Envoy-compatible sidecar proxy performing automated canary deployments based on real-time error rate thresholds and latency percentiles.",
             {"golang": 3, "docker": 3, "observability": 3}, 14, "none", 3, False, ["Go", "Envoy", "Docker", "Prometheus"])
        ]
    },
    {
        "domain": "Developer Tooling & Program Analysis",
        "ideas": [
            ("AST-Guard: Automated Static Analysis and Security Taint Engine for Python",
             "Abstract Syntax Tree (AST) visitor propagating untrusted user input sources into database and shell sinks to flag SQLi and command injection.",
             {"python": 4, "fastapi": 2, "react": 2}, 14, "CPU-only", 3, True, ["Python", "ast module", "FastAPI", "React"]),
            ("GitDrift: Real-Time Developer Velocity & Milestone Drift Predictor",
             "Engineering telemetry engine analyzing git commit graphs, PR turnaround latency, and churn ratios to predict sprint delivery slips.",
             {"python": 3, "fastapi": 3, "sql": 3, "data_viz": 3}, 12, "none", 3, False, ["Python", "FastAPI", "SQLite", "Recharts"]),
            ("DocuGen: Semantic Living Architecture Diagrams from Codebase Inspection",
             "Automated tool parsing package imports, REST route definitions, and database schemas into interactive editable C4 architecture models.",
             {"typescript": 3, "python": 3, "react": 3, "data_viz": 4}, 14, "none", 4, False, ["TypeScript", "Python", "React", "D3.js"]),
            ("TestShrink: Mutation Testing and Flaky Test Detection for CI Pipelines",
             "AST mutator injecting operator mutations into codebases to compute test suite mutation score and pinpoint untested conditional paths.",
             {"python": 4, "cicd": 3, "bash": 2}, 12, "none", 3, True, ["Python", "ast", "pytest", "GitHub Actions"]),
            ("TypeInfer: Probabilistic Runtime Type Inference for Dynamic Python",
             "Lightweight runtime profiling tracer inferring strict PEP 484 type annotations for untyped legacy codebases with zero test disruption.",
             {"python": 4, "fastapi": 2}, 12, "none", 2, True, ["Python", "sys.settrace", "mypy"]),
            ("BundleDoctor: Webpack/Vite Tree-Shaking Analyzer and Dead-Code Eliminator",
             "Static bundle graph inspector detecting phantom dependencies, duplicate polyfills, and CSS bloat to reduce frontend asset footprints.",
             {"typescript": 3, "web_performance": 3, "react": 2}, 10, "none", 2, False, ["TypeScript", "Rollup/Vite", "React"]),
            ("SchemaDiff: Zero-Downtime Database Migration Validator and Safety Linter",
             "CI pipeline check analyzing PostgreSQL DDL migration scripts for table locks, column drop hazards, and missing concurrent indexes.",
             {"python": 3, "postgresql": 3, "cicd": 3}, 10, "none", 2, False, ["Python", "PostgreSQL", "GitHub Actions"]),
            ("MockForge: Contract-Driven Dynamic Mock Server from OpenAPI 3.1 Specs",
             "Configurable API emulator generating stateful CRUD mocks, dynamic latency simulation, and schema validation from OpenAPI YAML.",
             {"typescript": 3, "nodejs": 3, "rest_apis": 3, "react": 2}, 10, "none", 3, False, ["TypeScript", "Node.js", "Express", "React"]),
            ("ProfileLens: Low-Overhead Sampling CPU Profiler with Interactive Flamegraphs",
             "POSIX signal-based sampling profiler recording call stacks at 100Hz and generating interactive SVG flamegraphs for performance bottlenecks.",
             {"cpp": 3, "python": 3, "data_viz": 3}, 14, "CPU-only", 3, True, ["C++", "Python", "SVG Flamegraphs", "D3.js"]),
            ("LintFlow: Unified Architectural Boundary Enforcer for Monorepos",
             "Static dependency linter verifying architectural boundaries (e.g. preventing domain entities from importing HTTP presentation controllers).",
             {"typescript": 3, "nodejs": 3, "cicd": 2}, 10, "none", 2, False, ["TypeScript", "Node.js", "GitHub Actions"])
        ]
    },
    {
        "domain": "Computer Vision & Spatial Computing",
        "ideas": [
            ("GazeTrack: WebCam-Only High-Precision Gaze and Attention Heatmapper",
             "Iris corneal reflection and head pose tracking using monocular webcam video to generate UX website eye-tracking attention heatmaps.",
             {"python": 3, "opencv": 4, "pytorch": 3, "data_viz": 3}, 14, "CPU-only", 4, True, ["Python", "OpenCV", "PyTorch", "D3.js", "FastAPI"]),
            ("AutoDefect: Real-Time High-Speed Surface Anomaly Detection on Industrial Conveyors",
             "Patch-based autoencoder locating microscopic scratches, voids, and misprints on manufactured parts moving at 1m/s.",
             {"python": 3, "pytorch": 3, "opencv": 3, "fastapi": 2}, 16, "GPU available", 4, True, ["Python", "PyTorch", "OpenCV", "FastAPI"]),
            ("VoxelNav: Real-Time Monocular 3D Occupancy Grid Mapping for Indoor Robotics",
             "Depth estimation and voxel raycasting pipeline turning a single RGB smartphone feed into a navigable 3D volumetric barrier map.",
             {"cpp": 3, "python": 3, "opencv": 3, "pytorch": 3}, 16, "GPU available", 4, True, ["C++", "Python", "OpenCV", "PyTorch"]),
            ("SignTranslate: Bidirectional Real-Time Sign Language Gesture Interpreter",
             "MediaPipe skeletal landmark tracker classifying continuous American Sign Language fingerspelling and converting gestures into audio speech.",
             {"python": 3, "opencv": 3, "scikit_learn": 3, "react": 2}, 12, "CPU-only", 3, True, ["Python", "OpenCV", "Scikit-Learn", "FastAPI", "React"]),
            ("NightVision: Extreme Low-Light Real-Time Video Enhancement via Retinex",
             "High-throughput neural Retinex decomposition illuminating pitch-black surveillance camera feeds with noise suppression in under 30ms.",
             {"python": 3, "pytorch": 3, "opencv": 3}, 14, "GPU available", 3, True, ["Python", "PyTorch", "OpenCV", "FastAPI"]),
            ("DocuWarp: Document Scanner Flattening and Perspective Rectification",
             "Geometric boundary contour detection and 3D surface unwarping to turn curved, crumpled book page photos into flat PDFs.",
             {"python": 3, "opencv": 4, "fastapi": 2}, 10, "CPU-only", 2, True, ["Python", "OpenCV", "NumPy", "FastAPI"]),
            ("CrowdCount: High-Density Crowd Estimation with Scale-Aware Dilated Convolutions",
             "Congestion density mapping for sports stadiums and transit hubs estimating headcount in crowds of up to 10,000 people.",
             {"python": 3, "pytorch": 3, "opencv": 3, "fastapi": 2}, 14, "GPU available", 3, True, ["Python", "PyTorch", "OpenCV", "FastAPI"]),
            ("SportVision: Automated Tennis/Badminton Shuttlecock Line-Call Verification",
             "High-framerate trajectory fitting and homography warping verifying in/out boundary calls with sub-centimeter parabolic physics models.",
             {"cpp": 3, "opencv": 4, "python": 2}, 14, "GPU available", 4, True, ["C++", "OpenCV", "Python"]),
            ("FaceShield: Real-Time Deepfake and Synthetic Video Telemetry Detector",
             "Facial blood flow photoplethysmography (rPPG) and eye-blink frequency analyzer exposing AI face swaps in live video calls.",
             {"python": 4, "opencv": 3, "pytorch": 3, "fastapi": 2}, 16, "GPU available", 4, True, ["Python", "PyTorch", "OpenCV", "FastAPI"]),
            ("MicroAlign: Sub-Pixel Electronic Component Soldering Alignment Inspector",
             "SMD circuit board surface mount inspection detecting bridging, Tombstoning, and component tilt on PCB assembly lines.",
             {"python": 3, "opencv": 4, "fastapi": 2}, 12, "CPU-only", 3, False, ["Python", "OpenCV", "FastAPI", "React"])
        ]
    },
    {
        "domain": "NLP & Knowledge Graphs",
        "ideas": [
            ("LegalSense: Automated Contract Clause Conflict Discovery via Cross-Attention",
             "RAG-grounded legal contract audit engine matching indemnification, liability, and termination clauses across 100-page master service agreements.",
             {"python": 3, "huggingface": 3, "vector_databases": 3, "fastapi": 2}, 14, "CPU-only", 4, True, ["Python", "FastEmbed", "Qdrant", "FastAPI", "React"]),
            ("CiteGraph: Interactive Scientific Research Paper Citations Knowledge Graph",
             "Academic paper recommendation engine constructing citation lineage graphs and surfacing foundational vs derivative research contributions.",
             {"python": 3, "vector_databases": 3, "data_viz": 4, "postgresql": 2}, 14, "none", 4, False, ["Python", "NetworkX", "PostgreSQL", "D3.js", "React"]),
            ("CodeWhisper: Local Privacy-First Code Autocompletion via Quantized LLM",
             "VS Code extension connecting to a local quantized 1B parameter code LLM running on CPU for zero-telemetry enterprise developers.",
             {"typescript": 3, "onnx_runtime": 3, "python": 2}, 14, "CPU-only", 3, True, ["TypeScript", "ONNX Runtime", "Python"]),
            ("DialectAI: Low-Resource Vernacular Language Speech-to-Text Pipeline",
             "Fine-tuned Whisper acoustic model adapted to regional colloquial dialects with acoustic data augmentation and beam search decoding.",
             {"python": 4, "huggingface": 3, "pytorch": 3}, 16, "GPU available", 4, True, ["Python", "PyTorch", "HuggingFace", "FastAPI"]),
            ("MedSummary: Clinical Patient Discharge Summary Generator with Grounding Check",
             "EHR summarization pipeline distilling doctor notes into patient-accessible guides with strict hallucination verification against vital signs.",
             {"python": 3, "vector_databases": 3, "llm_prompt_eng": 3, "fastapi": 2}, 12, "none", 3, True, ["Python", "FastAPI", "FAISS", "React"]),
            ("FactLens: Automated Claim Extraction and Multi-Source Fact-Checking",
             "NLP pipeline decomposing online news articles into atomic claims, querying trusted consensus archives, and assigning veracity scores.",
             {"python": 3, "vector_databases": 3, "huggingface": 3, "fastapi": 2}, 14, "none", 3, True, ["Python", "FastEmbed", "ChromaDB", "FastAPI"]),
            ("OntoMap: Automated Domain Ontology Construction from Unstructured Technical Text",
             "Relation extraction pipeline converting software documentation and engineering specs into structured RDF triples and knowledge graphs.",
             {"python": 3, "pandas_numpy": 3, "vector_databases": 2, "data_viz": 3}, 12, "none", 3, True, ["Python", "NetworkX", "FastAPI", "D3.js"]),
            ("BugSummarizer: GitHub Issue Triage and Duplicate Thread Clustering",
             "Semantic deduplication bot comparing incoming bug reports against open issues, suggesting root cause fixes from commit histories.",
             {"python": 3, "vector_databases": 3, "fastapi": 2, "docker": 2}, 12, "none", 3, False, ["Python", "FastEmbed", "FastAPI", "Docker"]),
            ("MeetingRecall: Multi-Speaker Meeting Transcript Action Item Extractor",
             "Speaker diarization and acoustic boundary segmentation producing structured sprint action item tickets with assignee tagging.",
             {"python": 3, "huggingface": 3, "fastapi": 2, "react": 2}, 12, "CPU-only", 3, False, ["Python", "HuggingFace", "FastAPI", "React"]),
            ("QueryAI: Natural Language to Secure SQL Query Translator with AST Validation",
             "NL-to-SQL translator enforcing read-only schema boundaries and AST validation to prevent data exfiltration and syntax errors.",
             {"python": 3, "sql": 3, "data_validation": 3, "fastapi": 2}, 10, "none", 3, True, ["Python", "SQLAlchemy", "FastAPI", "React"])
        ]
    }
]

all_ideas = []
idea_counter = 1
for cat in domains_data:
    domain_name = cat["domain"]
    for item in cat["ideas"]:
        title, desc, req_skills, timeline, hw, comp_cnt, novel_alg, stack = item
        lead_name = title.split(":")[0]
        idea_obj = {
            "id": f"idea-{idea_counter:03d}",
            "title": title,
            "domain": domain_name,
            "description": desc,
            "required_skills": req_skills,
            "typical_timeline_weeks": timeline,
            "hardware_requirement": hw,
            "component_count": comp_cnt,
            "novel_algorithm_required": novel_alg,
            "tech_stack": stack,
            "mvp_features": [
                f"Core pipeline implementation for {lead_name}",
                "Data ingestion, cleaning, and normalization module",
                "Validated REST API service with health monitoring"
            ],
            "stretch_features": [
                "Real-time telemetry dashboard with dynamic graphing",
                "Multi-node distributed clustering and automated failover",
                "Automated end-to-end integration test suite and CI deployment"
            ]
        }
        all_ideas.append(idea_obj)
        idea_counter += 1

output_path = "backend/data/idea_corpus.json"
os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, "w") as f:
    json.dump({"version": "1.0.0", "total_ideas": len(all_ideas), "ideas": all_ideas}, f, indent=2)

print(f"Successfully generated {len(all_ideas)} curated engineering ideas in {output_path}!")
