"""create_initial_production_schema

Revision ID: dddf2707dfe1
Revises: 
Create Date: 2026-09-05 11:59:08.127377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dddf2707dfe1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_students',
    sa.Column('cohort_id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('cohort_id', 'student_id')
    )
    op.create_table('cohorts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('faculty_id', sa.String(length=64), nullable=True),
    sa.Column('faculty_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('academic_year', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cohorts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cohorts_id'), ['id'], unique=False)

    op.create_table('department_archives',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department_archives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_archives_id'), ['id'], unique=False)

    op.create_table('generation_cache',
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cache_key')
    )
    with op.batch_alter_table('generation_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_cache_cache_key'), ['cache_key'], unique=False)

    op.create_table('mentor_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('sender', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentor_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentor_messages_project_id'), ['project_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=True),
    sa.Column('idea_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('mvp_features', sa.Text(), nullable=True),
    sa.Column('stretch_features', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.Text(), nullable=True),
    sa.Column('citations_json', sa.Text(), nullable=True),
    sa.Column('novelty_score', sa.Float(), nullable=True),
    sa.Column('feasibility_score', sa.Float(), nullable=True),
    sa.Column('hireability_score', sa.Float(), nullable=True),
    sa.Column('drift_status', sa.String(length=64), nullable=True),
    sa.Column('repo_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_student_id'), ['student_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('timeframe_weeks', sa.Integer(), nullable=True),
    sa.Column('hardware_constraint', sa.String(length=64), nullable=True),
    sa.Column('interest_domains', sa.Text(), nullable=True),
    sa.Column('skills_json', sa.Text(), nullable=True),
    sa.Column('selected_idea_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('cohort_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_user_id'))
        batch_op.drop_index(batch_op.f('ix_students_id'))

    op.drop_table('students')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_student_id'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    with op.batch_alter_table('mentor_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentor_messages_project_id'))

    op.drop_table('mentor_messages')
    with op.batch_alter_table('generation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_cache_cache_key'))

    op.drop_table('generation_cache')
    with op.batch_alter_table('department_archives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_archives_id'))

    op.drop_table('department_archives')
    with op.batch_alter_table('cohorts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cohorts_id'))

    op.drop_table('cohorts')
    op.drop_table('cohort_students')
    # ### end Alembic commands ###
